### ISSUE TITLE
Is it possible to process CoffeeScript files?

### ISSUE THREAD

**Issue by lmartins** [yyx990803/gulp-component#5]
Will the plugin allow to use coffee script files in the project components and still build valid JS?

**Comment by lmartins** [comment]
Sorry, i've missed the example for css:

```
gulp.task('styles', function () {
    gulp.src('component.json')
        .pipe(component.styles({
            configure: function (builder) {
                builder.use(stylus)
            }
        }))
        .pipe(gulp.dest('build/css'))
})
```

Im guessing for coffee script would be something like:

```
gulp.task('scripts', function () {
    gulp.src('component.json')
        .pipe(component.scripts({
            configure: function (builder) {
                builder.use(coffeescript)
            }
        }))
        .pipe(gulp.dest('build/js'))
})
```

Going to try this i'll reopen the question if I still can't get it to work.

**Comment by lmartins** [comment]
Actually im not finding a way to do this, can you confirm if it is possible?
The goal was to use Coffeescript on my custom components and have gulp-component compile that and include the compiled JS in the build file. Is this possible?

**Comment by yyx990803** [comment]
Are you using the official CoffeeScript compiler? With `builder.use` you need to use a plugin that's built specifically for Component's builder, e.g. https://www.npmjs.org/package/component-coffee

Also note Component 1.0 posted a bunch of breaking changes and `gulp-component` will likely have a breaking change coming soon too. But the above plugin should be working with the current version.

**Comment by lmartins** [comment]
Awesome, that did the trick, I was trying to run the default gulp compiler for coffeescript.
I was looking for this workflow for a long time. Thanks @yyx990803 Evan
